// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(connect, options) {
    var app, express, mountFolder, path, routes;

    express = require('express');
    routes = require('./routes');
    path = require('path');
    app = express();
    mountFolder = function(connect, dir) {
      return connect["static"](require('path').resolve(dir));
    };
    mountFolder(connect, options.base + '/../pub');
    app.configure(function() {
      app.set('views', options.base + '/views');
      app.set('view engine', 'jade');
      app.engine('.html', require('jade').__express);
      app.set('view options', {
        debug: true
      });
      app.use(express.logger('dev'));
      app.use(express.bodyParser());
      app.use(express.methodOverride());
      app.use(app.router);
      app.use(express.errorHandler());
      app.use(express["static"](options.base));
      app.use(function(err, req, res, next) {
        console.error(err.stack);
        return res.send(500, 'Something broke!');
      });
      return routes(app, options);
    });
    return connect(app).stack;
  };

}).call(this);
