// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(app, options) {
    var Client, DeepMerge, client, conf, merge;

    conf = {
      config: {
        environment: {}
      }
    };
    DeepMerge = require("deep-merge");
    merge = DeepMerge(function(target, source, key) {
      return [].concat(target, source);
    });
    Client = require('node-rest-client').Client;
    client = new Client();
    app.get('/', function(req, res) {
      return res.render("" + options.base + "/views/index", conf);
    });
    app.get('/entity', function(req, res) {
      return client.get("http://localhost:8080/yk-pagedata.json", function(data, response) {
        var c;

        console.log("got data");
        console.log(data);
        console.log("end data");
        c = merge(data, conf);
        console.log("merged data: ");
        console.log(c);
        return res.render("" + options.base + "/views/entity", c);
      }).on('error', function(err) {
        return console.log('something went wrong on the request', err.request.options);
      });
    });
    return app.get('/browse', function(req, res) {
      return client.get("http://localhost:8080/yk-browsedata.json", function(data, response) {
        return res.render("" + options.base + "/views/browse", merge(data, conf));
      }).on('error', function(err) {
        return console.log('something went wrong on the request', err.request.options);
      });
    });
  };

}).call(this);
