// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(app, options) {
    var conf, extend, rest;

    conf = {
      config: {
        environment: {}
      }
    };
    extend = require("xtend");
    rest = require('restler');
    app.get('/', function(req, res) {
      return res.render("" + options.base + "/views/index", conf);
    });
    app.get('/entity', function(req, res) {
      return rest.get('http://localhost:8088/api/entity/0').on('success', function(data, response) {
        var c;

        c = extend(conf, data);
        console.log("*** merged data");
        console.log(c);
        return res.render("" + options.base + "/views/entity", c);
      }).on('error', function(err) {
        return console.log('An error occurred:' + err);
      });
    });
    app.get('/browse', function(req, res) {
      return rest.get('http://localhost:8088/api/entities').on('success', function(data, response) {
        var c;

        c = extend(conf, data);
        console.log("*** merged data");
        console.log(c);
        return res.render("" + options.base + "/views/browse", c);
      }).on('error', function(err) {
        return console.log('An error occurred:' + err);
      });
    });
    return app.get('/topic', function(req, res) {
      return rest.get('http://localhost:8088/api/topic/0').on('success', function(data, response) {
        var c;

        c = extend(conf, data);
        console.log("*** merged data");
        console.log(c);
        return res.render("" + options.base + "/views/topic", c);
      }).on('error', function(err) {
        return console.log('An error occurred:' + err);
      });
    });
  };

}).call(this);
